### ISSUE TITLE
Unable to obtain the worker node

### ISSUE THREAD

**Issue by testQx** [codedog-ai/codedog#134]
I try to scan C++ code here, when running cppcheck2, always report an error node executable tool process: 0, sometimes normal, but often times stuck, how to configure timeout, or avoid this situation

![image](https://github.com/codedog-ai/codedog/assets/61589114/3940666f-6fea-4361-a2ed-d1e817fc1a28)

**Comment by Arcadia822** [comment]
it looks like another codedog project's problem.
